-intstyle "ise" -incremental -o "D:/GitHub/VHDL_Modules/Digital Snake Wing/Test/Test_tbench_isim_beh.exe" -prj "D:/GitHub/VHDL_Modules/Digital Snake Wing/Test/Test_tbench_beh.prj" "work.Test_tbench" 
